# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NorthLoopFin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'AFNetworking', '~> 3.0'

  pod 'SVProgressHUD'

  pod 'ReachabilitySwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManagerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Auth0', '~> 1.5'
  pod 'MFSideMenu'
  pod 'PWSwitch'
  pod 'DropDown', '2.3.2'
  pod 'HockeySDK', '~> 5.1.4'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Repeat'

  # Pods for NorthLoopFin

  target 'NorthLoopFinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NorthLoopFinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
