# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NorthLoopFin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'AFNetworking', '~> 3.0'

  pod 'SVProgressHUD'

  pod 'ReachabilitySwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for NorthLoopFin

  target 'NorthLoopFinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NorthLoopFinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
