# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NorthLoopFin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'AFNetworking', '~> 3.0'
  pod 'SVProgressHUD'
  pod 'ReachabilitySwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManagerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'MFSideMenu'
  pod 'PWSwitch'
  pod 'DropDown', '2.3.2'
  pod 'HockeySDK', '~> 5.1.4'
  pod 'Repeat'
  pod 'Amplitude-iOS', '~> 4.5'
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 5.0'
  pod 'ZendeskSDK', '3.0.0'
  pod 'GiFHUD-Swift'
  pod 'ZDCChat'
  pod 'SwiftyRSA'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Haptica'
  pod 'AlertHelperKit', :git => 'https://github.com/keygx/AlertHelperKit'
  pod 'SwiftKeychainWrapper'
  pod "ESTabBarController-swift"
  pod 'RKPieChart'

  # Pods for NorthLoopFin

  target 'NorthLoopFinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NorthLoopFinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
